mappings:
  # System layer
  - name: system-env
    src: system/etc/aila/
    dst: /etc/aila/
    sudo: true
    description: "Environment fragments and shared configuration"

  - name: system-opt
    src: system/opt/aila/
    dst: /opt/aila/
    sudo: true
    description: "Shared runtime directories and data roots"

  - name: system-logs
    src: system/var/log/aila/
    dst: /var/log/aila/
    sudo: true
    description: "Log directories with correct ownership"

  # Core cognition
  - name: aila-core
    src: aila/
    dst: /opt/aila/core/
    sudo: true
    description: "Python package with perception, planning, and interfaces"

  # Shared scripts
  - name: scripts-bin
    src: scripts/
    dst: /usr/local/bin/
    sudo: true
    description: "Administration scripts for install, deploy, and runtime"

  # Services: Whisper
  - name: whisper-systemd
    src: services/whisper/systemd/
    dst: /etc/systemd/system/
    sudo: true
    description: "Whisper ASR service unit"

  - name: whisper-config
    src: services/whisper/config/
    dst: /etc/aila-whisper/
    sudo: true
    description: "Whisper inference settings"

  - name: whisper-main
    src: services/whisper/main/
    dst: /opt/aila/whisper/
    sudo: true
    description: "Whisper runtime scripts"

  - name: whisper-scripts
    src: services/whisper/scripts/
    dst: /opt/aila/whisper/bin/
    sudo: true
    description: "Whisper utility tools"

  # Services: Coqui TTS
  - name: coqui-systemd
    src: services/coqui/systemd/
    dst: /etc/systemd/system/
    sudo: true
    description: "Coqui TTS service unit"

  - name: coqui-config
    src: services/coqui/config/
    dst: /etc/aila-coqui/
    sudo: true
    description: "Coqui TTS configuration"

  - name: coqui-main
    src: services/coqui/main/
    dst: /opt/aila/coqui/
    sudo: true
    description: "Coqui TTS runtime scripts"

  # Services: Monitor
  - name: monitor-systemd
    src: services/monitor/systemd/
    dst: /etc/systemd/system/
    sudo: true
    description: "Aila monitor service unit"

  - name: monitor-config
    src: services/monitor/config/
    dst: /etc/aila-monitor/
    sudo: true
    description: "Monitor configuration and dashboards"

  - name: monitor-main
    src: services/monitor/main/
    dst: /opt/aila/monitor/
    sudo: true
    description: "Monitor data collectors"

  - name: monitor-scripts
    src: services/monitor/scripts/
    dst: /opt/aila/monitor/bin/
    sudo: true
    description: "Monitor helper scripts"

exclude_file: deploy/rsync-exclude.txt

sync_policy:
  mode: mirror
  dry_run: true
  backup: true
  preserve_permissions: true
  show_progress: true
